export default {
	SET_AUTH_STATUS      : 'SET_AUTH_STATUS',
	ADD_FORM_QUESTION    : 'ADD_FORM_QUESTION',
	DELETE_FORM_QUESTION : 'DELETE_FORM_QUESTION',
	EDIT_FORM_FIELD      : 'EDIT_FORM_FIELD',
	EDIT_FORM_QUESTION   : 'EDIT_FORM_QUESTION',
	UPDATE_QUESTION_POSITION : 'UPDATE_QUESTION_POSITION',
	EDIT_MULTIPLE_CHOICE_OPTION : 'EDIT_MULTIPLE_CHOICE_OPTION',
	TOGGLE_FORM_QUESTION_REQUIRED : 'TOGGLE_FORM_QUESTION_REQUIRED'
};