export default {
	FETCH_AUTH_STATUS             : 'FETCH_AUTH_STATUS',
	FETCH_AUTH_STATUS_SUCCESS     : 'FETCH_AUTH_STATUS_SUCCESS',
	FETCH_AUTH_STATUS_ERROR       : 'FETCH_AUTH_STATUS_ERROR',

	ADD_FORM_QUESTION             : 'ADD_FORM_QUESTION',
	DELETE_FORM_QUESTION          : 'DELETE_FORM_QUESTION',
	EDIT_QUESTION                 : 'EDIT_QUESTION',
	EDIT_FORM_FIELD               : 'EDIT_FORM_FIELD',
	UPDATE_QUESTION_POSITION      : 'UPDATE_QUESTION_POSITION',
	EDIT_MULTIPLE_CHOICE_OPTION   : 'EDIT_MULTIPLE_CHOICE_OPTION',
	TOGGLE_FORM_QUESTION_REQUIRED : 'TOGGLE_FORM_QUESTION_REQUIRED',
	
	SIGN_OUT                      : 'SIGN_OUT',
	SIGN_OUT_SUCCESS              : 'SIGN_OUT_SUCCESS',
	SIGN_OUT_ERROR                : 'SIGN_OUT_ERROR',

	CREATE_FORM : 'CREATE_FORM',
	CREATE_FORM_SUCCESS : 'CREATE_FORM_SUCCESS',
	CREATE_FORM_ERROR : 'CREATE_FORM_ERROR',

	EDIT_FORM : 'EDIT_FORM',
	EDIT_FORM_SUCCESS : 'EDIT_FORM_SUCCESS',
	EDIT_FORM_ERROR : 'EDIT_FORM_ERROR',

	FETCH_FORM         : 'FETCH_FORM',
	FETCH_FORM_SUCCESS : 'FETCH_FORM_SUCCESS',
	FETCH_FORM_ERROR   : 'FETCH_FORM_ERROR'
};